apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  namespaceSelector:
    matchNames:
      - deepseek-aibrix
  endpoints:
    - port: serve
      path: /metrics
      interval: 15s
